// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace DelegatePro.iOS
{
	public partial class NotesTableViewCell : UITableViewCell
	{
		private const string CellIdentifier = "NotesTableViewCell";
        public NotesTableViewCell(IntPtr handle) : base(handle)
        {
        }

        public static UITableViewCell Dequeue(UITableView tableView, string labelText, bool isAddressed)
        {
            var cell = (NotesTableViewCell)tableView.DequeueReusableCell(CellIdentifier);

            cell.NotesLabel.Text = labelText;

            cell.NotesAddressedLabel.BackgroundColor = (isAddressed) ? UIColor.Green : UIColor.White;

            var layer = cell.NotesAddressedLabel.Layer;
            layer.CornerRadius = 6f;
            layer.MasksToBounds = true;
            layer.BorderWidth = (isAddressed) ? 0 : 1;
            layer.BorderColor = (isAddressed) ? UIColor.Green.CGColor : UIColor.Gray.CGColor;

            return cell;
        }
	}
}
