// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace DelegatePro.iOS
{
    public partial class SwitchCell : BaseTableViewCell
	{
        private NoteDetailsViewController NoteDetailVC => ParentVC as NoteDetailsViewController;

        private const string CellIdentifier = "SwitchCell";
		public SwitchCell (IntPtr handle) : base (handle)
		{
		}

        public void SetupClickEvents()
        {
            Switch.ValueChanged -= Switch_ValueChanged;
            Switch.ValueChanged += Switch_ValueChanged;
        }

        public static UITableViewCell Dequeue(BaseViewController parentVC, UITableView tableView, string labelText, bool isOnValue)
        {
            var cell = (SwitchCell)tableView.DequeueReusableCell(CellIdentifier);
            cell.ParentVC = parentVC;

            cell.TextLabel.Text = labelText;
            cell.Switch.On = isOnValue;

            cell.SetupClickEvents();
            return cell;
        }

        private void Switch_ValueChanged(object sender, EventArgs e)
        {
            NoteDetailVC?.UpdateAddressed(Switch.On);
        }
    }
}
